name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -fsSL https://astral.sh/uv/install.sh | bash
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Check directory structure
      run: |
        echo "Checking directory structure..."
        ls -la
        echo "Contents of scripts directory (if exists):"
        ls -la scripts || echo "scripts directory not found"

    - name: Test with pytest
      env:
        MESHY_API_KEY: ${{ secrets.MESHY_API_KEY }}
        PYTEST_MOCK_MODE: "true"
      run: |
        source .venv/bin/activate
        # Skip the diagnostic script if it doesn't exist
        if [ -f "scripts/diagnose_tests.py" ]; then
          echo "Running diagnostic script..."
          python scripts/diagnose_tests.py || true
        else
          echo "Diagnostic script not found. Skipping..."
        fi
        # Run the actual tests with correct coverage path
        python -m pytest tests/ --cov=src.python_jewelry_design_gen --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
